[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run build:frontend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "wedding-photo-app"
source = "."

[services.variables]
NODE_ENV = "production"
PORT = "3000"